#!/bin/bash
# Day 7 scenario setup — the rogue process from Day 6 is back, and this time
# killing it doesn't stick: something respawns it every few seconds. For
# crontab file investigation (/var/spool/cron/crontabs), pgrep -f, and
# process-tree thinking (kill the persistence mechanism, not just the symptom).
# Safe to re-run: kills any previous instances, then wipes and rebuilds mission/.

BASE="$(dirname "$0")/mission"

pkill -f "$BASE/" 2>/dev/null
sleep 0.2

rm -rf "$BASE"
mkdir -p "$BASE/opt"
mkdir -p "$BASE/var/spool/cron/crontabs"

cat > "$BASE/opt/rogue_watcher.sh" <<'EOF'
#!/bin/bash
DIR="$(dirname "$0")"
LOG="$DIR/watcher.log"
FLAG_FILE="$DIR/../recovered.flag"

cleanup() {
  echo "$(date +%T) received SIGTERM - shutting down" >> "$LOG"
  if pgrep -f "$DIR/respawn_daemon.sh" >/dev/null; then
    echo "$(date +%T) persistence mechanism still active - expect a respawn" >> "$LOG"
  else
    echo "$(date +%T) persistence mechanism is gone - staying down for good" >> "$LOG"
    echo "FLAG{cron_persistence_defeated}" > "$FLAG_FILE"
  fi
  exit 0
}
trap cleanup SIGTERM

echo "$(date +%T) rogue_watcher started, pid $$" >> "$LOG"
while true; do
  echo "$(date +%T) heartbeat - unauthorized process (owner: hassan.ali)" >> "$LOG"
  sleep 3
done
EOF
chmod +x "$BASE/opt/rogue_watcher.sh"

cat > "$BASE/opt/respawn_daemon.sh" <<'EOF'
#!/bin/bash
DIR="$(dirname "$0")"
WATCHER="$DIR/rogue_watcher.sh"
LOG="$DIR/respawn_daemon.log"

echo "$(date +%T) respawn_daemon started, pid $$" >> "$LOG"
while true; do
  if ! pgrep -f "$WATCHER" >/dev/null; then
    echo "$(date +%T) watcher not running - respawning it (see crontab entry)" >> "$LOG"
    nohup "$WATCHER" >/dev/null 2>&1 &
    disown
  fi
  sleep 4
done
EOF
chmod +x "$BASE/opt/respawn_daemon.sh"

cat > "$BASE/var/spool/cron/crontabs/hassan.ali" <<EOF
# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (Sandboxed copy for this exercise: the real "crontab" command isn't wired
# up here, but this is the actual file format and the actual path — on a
# real box, user crontabs live under /var/spool/cron/crontabs/<user>.)
*/1 * * * * $BASE/opt/respawn_daemon.sh >> $BASE/opt/respawn_daemon.log 2>&1
EOF

nohup "$BASE/opt/rogue_watcher.sh" >/dev/null 2>&1 &
disown
nohup "$BASE/opt/respawn_daemon.sh" >/dev/null 2>&1 &
disown

echo "Mission environment built at: $BASE"
echo "The rogue process from Day 6 is back. Kill it — watch it come back too."
echo "Something is respawning it. Find the mechanism, stop that first, then"
echo "finish the job."
